volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    expose:
      - "8000"
      - "5432"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    command: postgres -c max_connections=200
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  flower:
    <<: *django
    image: local_flower
    depends_on:
      - redis
    ports:
      - "5555:5555"
    command: /start-flower

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
