#!/bin/sh

set -o errexit
set -o nounset

# Caddy strips /flower before proxying (handle_path), but --url-prefix tells
# Flower to generate all its internal links with /flower so navigation works.
celery -A config.celery --broker="${CELERY_BROKER_URL}" flower \
    --url-prefix=/flower
